environments:
    - name: dev
      configs:
          endpoints:
              production:
                  url: 'https://pet.dev.wso2.com'
              sandbox:
                  url: 'https://pet.dev.sandbox.wso2.com'
    - name: prod
      configs:
          endpoints:
              production:
                  url: 'https://pet.prod.wso2.com'
              sandbox:
                  url: 'https://pet.prod.sandbox.wso2.com'