environments:
    - name: dev
      configs:
          endpoints:
              production:
                  url: 'https://pizza.dev.wso2.com'
              sandbox:
                  url: 'https://pizza.dev.sandbox.wso2.com'
    - name: prod
      configs:
          endpoints:
              production:
                  url: 'https://pizza.prod.wso2.com'
              sandbox:
                  url: 'https://pizza.prod.sandbox.wso2.com'